package main;

import model.CuentaBancaria;
//import model.CuentaAhorros;
//import model.CuentaCorriente;
//import model.CuentaPlazoFijo;
import model.SaldoInsuficienteException;
//import model.LimiteRetiroExcedidoException;
//import java.util.ArrayList;
import controller.CuentaBancariaController;


public class BancaExclusivaForm extends javax.swing.JFrame {
    private java.util.ArrayList<model.CuentaBancaria> listaCuentas;
    private CuentaBancariaController controller;

    private void inicializarCuentasDelBanco() {
        this.controller = new CuentaBancariaController();

        System.out.println("--- Cargando cuentas mediante el Controlador (MVC) ---");
        listaCuentas = (java.util.ArrayList<model.CuentaBancaria>) controller.listarCuentas();
        System.out.println("--- Cuentas cargadas: " + listaCuentas.size() + " ---");

        // Si por alguna razón la base de datos estuviera vacía, puedes dejar una de respaldo:
        if (listaCuentas.isEmpty()) {
            System.out.println("La base de datos está vacía. Registrando cuentas iniciales de prueba...");
            model.CuentaBancaria c1 = new model.CuentaAhorros("191-456789-0-12", "Juan Carlos Alzamora", 2000.0, "15/01/2026", 0.02, 500.0);
            model.CuentaBancaria c2 = new model.CuentaCorriente("191-987654-3-45", "Ana Maria Lopez", 1500.0, "10/02/2026", 1000.0);
            model.CuentaBancaria c3 = new model.CuentaPlazoFijo("191-112233-4-88", "Pedro Pablo Kuczynski", 10000.0, "01/03/2026", "01/09/2026", 6);

            controller.registrarCuenta(c1);
            controller.registrarCuenta(c2);
            controller.registrarCuenta(c3);

            listaCuentas = (java.util.ArrayList<model.CuentaBancaria>) controller.listarCuentas();
        }
    }

    private model.CuentaBancaria obtenerCuentaSeleccionada() {
        int indiceSeleccionado = cmbCuentas.getSelectedIndex();
        // El ArrayList recupera el elemento usando .get() en lugar de []
        return listaCuentas.get(indiceSeleccionado);
    }

    private void actualizarPantalla() {
        StringBuilder sb = new StringBuilder();
        sb.append("=========================================\n");
        sb.append("         ESTADO DE CUENTAS ACTUALIZADO    \n");
        sb.append("=========================================\n\n");
        
        // Recorremos el ArrayList polimórficamente sin importar cuántas cuentas existan
        for (model.CuentaBancaria cuenta : listaCuentas) {
            sb.append("-> Tipo: ").append(cuenta.getClass().getSimpleName()).append("\n");
            sb.append("   ").append(cuenta.generarEstadoCuenta()).append("\n");
            sb.append("-----------------------------------------------------------------\n");
        }
        
        txtAreaConsola.setText(sb.toString());
    }
    
    public BancaExclusivaForm() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana
        inicializarCuentasDelBanco();
        actualizarPantalla();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCuentas = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        btnDepositar = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        btnInteres = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaConsola = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO VALLEJO S.A.C.");

        cmbCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuenta de Ahorros", "Cuenta Corriente", "Cuenta a Plazo Fijo" }));

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });

        btnInteres.setText("Calcular Interes");
        btnInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione Cuenta:");

        jLabel2.setText("Monto S/.");

        txtAreaConsola.setEditable(false);
        txtAreaConsola.setColumns(20);
        txtAreaConsola.setRows(5);
        jScrollPane1.setViewportView(txtAreaConsola);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(btnDepositar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnRetirar)
                                .addGap(29, 29, 29)
                                .addComponent(btnInteres))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDepositar)
                    .addComponent(btnRetirar)
                    .addComponent(btnInteres))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        try {
        double monto = Double.parseDouble(txtMonto.getText());
        model.CuentaBancaria cuentaActiva = obtenerCuentaSeleccionada();
        
        if (cuentaActiva != null) {
            // La vista delega la operación al controlador
            boolean exito = controller.depositar(cuentaActiva, monto);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Depósito procesado con éxito.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar en Base de Datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            txtMonto.setText(""); 
            actualizarPantalla(); 
        }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un monto numérico válido.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        try {
        double monto = Double.parseDouble(txtMonto.getText());
        model.CuentaBancaria cuentaActiva = obtenerCuentaSeleccionada();
        
        if (cuentaActiva != null) {
            // La vista delega el retiro y la persistencia al controlador
            boolean exito = controller.retirar(cuentaActiva, monto);
            
            if (exito) {
                javax.swing.JOptionPane.showMessageDialog(this, "Retiro procesado con éxito.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al actualizar en Base de Datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            txtMonto.setText("");
            actualizarPantalla();
        }
        } catch (SaldoInsuficienteException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Saldo Insuficiente", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Atención", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnRetirarActionPerformed

    private void btnInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresActionPerformed
        CuentaBancaria cuentaActiva = obtenerCuentaSeleccionada();
        double interesGenerado = cuentaActiva.calcularInteres();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Interés calculado para " + cuentaActiva.getClass().getSimpleName() + 
                "\nMonto Abonado: S/. " + interesGenerado, "Intereses Aplicados", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        actualizarPantalla();
    }//GEN-LAST:event_btnInteresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancaExclusivaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancaExclusivaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancaExclusivaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancaExclusivaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancaExclusivaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnInteres;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JComboBox<String> cmbCuentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaConsola;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
